In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
import matplotlib.pyplot as plt 
plt.rc("font", size=14)
from sklearn.linear_model import LogisticRegression
from sklearn.cross_validation import train_test_split
import seaborn as sns
sns.set(style="white")
sns.set(style="whitegrid", color_codes=True)

C:\Users\Mayank\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [4]:
data = pd.read_csv('PrepData.csv', header=0)
data = data.dropna()
print(data.shape)
print(list(data.columns))

(334, 7)
['NAME', 'PERCENTAGE', 'BACKLOG', 'INTERNSHIP', 'FIRSTROUND', 'COMMUNICATION SKILLLS', 'Hired']


In [8]:
data

NAME  PERCENTAGE  BACKLOG  INTERNSHIP  FIRSTROUND  \
0          Apaar Gupta          99      0.0           3          90   
1        Aastha Khanna          92      0.0           3          68   
2          Yogita Rana          84      3.0           2          69   
3                 Kush          67      2.0           2          23   
4        Pulkit Mittal          57      0.0           2          78   
5       Gaurav Gambhir          85      0.0           1          86   
6           Shruti Jha          82      0.0           3          61   
7    Ayush Vishwakarma          47      0.0           2          32   
8            Divyanshu          62      2.0           1          56   
9               Ashish          67      1.0           0          45   
10            Jigyasha          56      4.0           2          78   
11               Mehar          68      2.0           1          23   
12       Arushi Bhalla          65      2.0           3          90   
13      Pooja Vacchani          89      0.0           3          45   
14            Shrishti          45      3.0           2          67   
15       Rajesh Sharma          67      0.0           3          89   
16               Divya          45      2.0           1          34   
17         Ritu Sharma          67      0.0           2          56   
18     Muskaan Jhanjee          69      1.0           0          78   
19            Shahrukh          78      2.0           0          82   
20         Tarun Karan          89      0.0           1          76   
21       Harshit Kumar          67      0.0           3          89   
22         Nitin Karan          34      0.0           2          34   
23     Nishant Dhankar          90      0.0           1          56   
24   Bhavya Pachananda          76      1.0           0          78   
25         Ajay Sharma          87      2.0           0          56   
26          Aman Arora          45      0.0           1          76   
27      Utkarsh Sharma          72      2.0           3          67   
28               Kohli          65      3.0           1          75   
29       Nikhil Sharma          84      2.0           2          84   
..                 ...         ...      ...         ...         ...   
305           abhishek          72      1.0           4          80   
306             prince          99      0.0           5          95   
307              aryan          88      1.0           3          89   
308              raman          73      2.0           4          82   
309              samar          80      1.0           2          69   
310    Krishna purohit          97      0.0           5          89   
311        shubhashish          86      0.0           3          85   
312     Ramesh purohit          89      0.0           2          87   
313     Suresh purohit          67      0.0           3          89   
314  devashish purohit          87      0.0           3          86   
315      Mamta purohit          69      0.0           4          85   
316    Santosh purohit          89      0.0           5          88   
317    divakar purohit          83      0.0           4          87   
318     Mukesh purohit          91      0.0           4          90   
319     archana pareek          94      0.0           3          91   
320        Damodar Das          78      0.0           1          67   
321            Kanchan          80      2.0           3          80   
322      Gaurav sharma          86      0.0           2          89   
323            Gayatri          57      0.0           2          78   
324               Yash          78      0.0           2          68   
325             Sambit          87      0.0           3          70   
326           Priyanka          50      0.0           3          80   
327              Rajat          74      1.0           4          78   
328      Kumar Vishwas          79      0.0           1          79   
329             Farhan          56      2.

In [11]:
X = data.iloc[:,[1,5]].values
y = data.iloc[:,6].values

In [12]:
# evaluate the model aby splititng into the tarin tests sets 
X_train, X_test, y_train , y_test= train_test_split(X,y,test_size=0.3, random_state=0)

In [13]:
from sklearn.preprocessing import StandardScaler
SC_X = StandardScaler()
X_train = SC_X.fit_transform(X_train)
X_test = SC_X.fit_transform(X_test)

C:\Users\Mayank\AppData\Local\Enthought\Canopy\edm\envs\User\lib\site-packages\sklearn\utils\validation.py:429: DataConversionWarning: Data with input dtype int64 was converted to float64 by StandardScaler.
  warnings.warn(msg, _DataConversionWarning)


In [14]:
model=LogisticRegression(random_state=0)
model.fit(X_train, y_train)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='ovr', n_jobs=1,
          penalty='l2', random_state=0, solver='liblinear', tol=0.0001,
          verbose=0, warm_start=False)

In [16]:
y_pred = model.predict(X_test)
print(y_pred)

[1 1 0 1 0 0 1 1 1 0 0 1 0 0 0 1 1 0 1 1 1 0 0 1 0 1 0 1 0 0 0 0 1 0 1 0 1
 1 0 1 0 0 1 0 1 1 1 1 1 0 1 1 0 0 0 1 0 0 0 1 1 1 1 0 0 1 0 1 0 1 1 0 0 1
 0 0 1 1 1 0 0 1 1 1 0 0 1 1 0 1 1 1 1 1 1 0 0 1 0 0 1]


In [17]:
probs = model.predict_proba(X_test)
print(probs)

[[ 0.20783611  0.74729626  0.02510472  0.01976291]
 [ 0.17018517  0.77544726  0.02094429  0.03342328]
 [ 0.90656167  0.02896504  0.00661201  0.05786128]
 [ 0.26843833  0.6907761   0.02958061  0.01120496]
 [ 0.67838678  0.28469843  0.01709032  0.01982447]
 [ 0.91407233  0.05223213  0.01129531  0.02240024]
 [ 0.27713839  0.67837171  0.02274887  0.02174103]
 [ 0.09299664  0.85599145  0.02631878  0.02469313]
 [ 0.01713736  0.92595551  0.03831996  0.01858717]
 [ 0.86699985  0.08399089  0.00973329  0.03927596]
 [ 0.90535499  0.06856085  0.01731429  0.00876986]
 [ 0.01658829  0.92639376  0.04221438  0.01480358]
 [ 0.59453236  0.31856948  0.00995492  0.07694324]
 [ 0.5891623   0.37678034  0.02646603  0.00759134]
 [ 0.72316833  0.23537535  0.01436539  0.02709092]
 [ 0.29814627  0.65807371  0.02259916  0.02118086]
 [ 0.04685301  0.89673122  0.02719517  0.0292206 ]
 [ 0.58449401  0.36527803  0.01457743  0.03565054]
 [ 0.41819947  0.5078285   0.0130427   0.06092934]
 [ 0.31268958  0.6434102   0.02

In [20]:
model.predict_proba(np.array([75,86]).reshape(1,-1))

array([[  6.29426757e-89,   4.99999966e-01,   4.99999966e-01,
          6.79102070e-08]])